language: objective-c
osx_image: xcode8.3
xcode_project: PureSegue.xcodeproj
xcode_sdk: iphonesimulator10.2

before_install: 
- rvm install 2.1.0
- rvm use $RVM_RUBY_VERSION

install: 
- bundle install

script: 
- xcodebuild -project PureSegue.xcodeproj -scheme PureSegue build -sdk iphonesimulator
- xcodebuild test -project PureSegue.xcodeproj -scheme PureSegue build -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'

after_success: 
- slather

notifications:
  email:
    on_success: never
