language: objective-c
osx_image: xcode8.3
xcode_project: PureSwift.xcodeproj
xcode_sdk: iphonesimulator10.2

script: 
- xcodebuild -project PureSwift.xcodeproj -scheme PureSwift build -sdk iphonesimulator
- xcodebuild test -project PureSwift.xcodeproj -scheme PureSwift build -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'

