language: objective-c
xcode_project: PureSegue.xcodeproj

before_install: 
- rvm install 2.1.0
- rvm use $RVM_RUBY_VERSION

install: 
- bundle install

script:
  - script/build
  
env:
  global:
    - XCODE_SDK=iphonesimulator
    - XCODE_ACTION="test"
    - CONFIGURATION=Debug

matrix:
  include:
      - xcode_scheme: PureSegue
        osx_image: xcode8.3
        env: XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 7"
      - xcode_scheme: PureSegue
        osx_image: xcode8.3
        env: XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 5"
      - xcode_scheme: PureSegue
        osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6"
      - xcode_scheme: PureSegue
        osx_image: xcode8.2
        env: XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 5"

after_success: 
- slather

notifications:
  email:
    on_success: never
