#!/bin/bash

BUILD_DIRECTORY="build"

if [[ -z $TRAVIS_XCODE_PROJECT ]]; then
    echo "Error: \$TRAVIS_XCODE_WORKSPACE is not set."
    exit 1
fi

if [[ -z $XCODE_ACTION ]]; then
    echo "Error: \$XCODE_ACTION is not set!"
    exit 1
fi

if [[ -z $TRAVIS_XCODE_SCHEME ]]; then
    echo "Error: \$TRAVIS_XCODE_SCHEME is not set!"
    exit 1
fi

if [[ -z $XCODE_SDK ]]; then
    echo "Error: \$XCODE_SDK is not set!"
    exit 1
fi

if [[ -z $XCODE_DESTINATION ]]; then
    echo "Error: \$XCODE_DESTINATION is not set!"
    exit 1
fi

if [[ -z $CONFIGURATION ]]; then
    echo "Error: \$CONFIGURATION is not set!"
    exit 1
fi

xcodebuild -version

result=$(xcodebuild $XCODE_ACTION \
    -project "$TRAVIS_XCODE_PROJECT" \
    -scheme "$TRAVIS_XCODE_SCHEME" \
    -sdk "$XCODE_SDK" \
    -destination "$XCODE_DESTINATION" \
    -configuration $CONFIGURATION \
    ENABLE_TESTABILITY=YES \
    GCC_GENERATE_DEBUGGING_SYMBOLS=NO \
    RUN_CLANG_STATIC_ANALYZER=NO | xcpretty)

if [ "$result" -ne 0 ]; then
    exit $result
fi
